### ISSUE TITLE
RDKit Conversion Issue

### ISSUE THREAD

**Issue by zachcp** [biotite-dev/biotite#756]
Hi @padix-key ,

As a follow up to https://github.com/zachcp/moltite/issues/1, I just tried to use this new feature and the conversion gives me an empty stack. I can track this down if needed but do you think you could confirm if this is reproducible on your end? 

```python

import rdkit
import biotite

print(biotite.__version__)
print(rdkit.__version__)
# 1.1.1.dev43+g4c7204af
# 2024.09.5


from rdkit import Chem
from biotite.interface import rdkit as irdk

# Example SMILES string
smiles = "CC(=O)OC1=CC=CC=C1"  # Aspirin

# Convert SMILES to mol object
mol = Chem.MolFromSmiles(smiles)

biotite_mol = irdk.from_mol(mol)
biotite_mol

# the conversion gives me an empty stack...
# stack([ ])
```

**Comment by zachcp** [comment]
I can confirm the above with this minimal env. This is python 3.13. 

```toml
# pixi.toml
[project]
authors = ["Zachary Charlop-Powers <zach.charlop.powers@gmail.com>"]
channels = ["conda-forge"]
name = "test"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
rdkit = ">=2024.9.5,<2025"
ipython = ">=8.32.0,<9"

[pypi-dependencies]
biotite = { git = "https://github.com/biotite-dev/biotite", rev = "4c7204afd07c489117243fd8ad4a67f787a4a820" }

```
